// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// For Prisma Postgres with Accelerate:
// - DATABASE_URL = Accelerate connection string (prisma://) - used by the app
// - DIRECT_DATABASE_URL = Direct PostgreSQL connection string - used for migrations
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
